version: '3'

services:
  processing-node:
    build:  ./processing-node
    depends_on:
      - group-definer
    environment:
      app.consumer.topics: "AppModel"
      app.consumer.auto.offset.reset: "latest"
      app.consumer.bootstrap.servers: "kafka1:6110"    # aqui
      app.consumer.group.id: "gw-consumer"
      app.producer.bootstrap.servers: "kafka1:6110"    # aqui
      app.producer.retries: "3"
      app.producer.enable.idempotence: "true"
      app.producer.linger.ms: "1"
      app.producer.acks: "all"
    volumes:
      - /workspaces/INF1304-Trabalho1/data/users.json:/users.json
      - /workspaces/INF1304-Trabalho1/data/turmas.json:/turmas.json
      - /workspaces/INF1304-Trabalho1/data/groups_log.csv:/groups_log.csv
      - /workspaces/INF1304-Trabalho1/data/attendance_log.csv:/attendance_log.csv
      - /workspaces/INF1304-Trabalho1/data/presence_table.csv:/presence_table.csv
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  group-definer:
    build:  ./group-definer
    environment:
      gd.one.consumer.topics: "GroupReportTopic"
      gd.one.consumer.auto.offset.reset: "latest"
      gd.one.consumer.bootstrap.servers: "kafka1:6110"   # aqui
      gd.one.consumer.group.id: "gw-gd"
      gd.one.producer.bootstrap.servers: "kafka1:6110"   # aqui
      gd.one.producer.retries: "3"
      gd.one.producer.enable.idempotence: "true"
      gd.one.producer.linger.ms: "1"
    volumes:
      - /workspaces/INF1304-Trabalho1/data/users.json:/users.json
      - /workspaces/INF1304-Trabalho1/data/turmas.json:/turmas.json
      - /workspaces/INF1304-Trabalho1/data/groups_log.csv:/groups_log.csv
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
        